-- Nitin Nabin site — seed data (matches lib/seed.ts)
-- Run AFTER migrations/20260910000000_init.sql in Supabase → SQL Editor.

-- Updates ---------------------------------------------------------------
insert into public.updates (event_date, kind_en, kind_hi, title_en, title_hi, summary_en, summary_hi, place_en, place_hi, image_url, sort_order) values
('2026-08-18','Event','कार्यक्रम','Addressed the extended State Executive meeting','विस्तारित प्रदेश कार्यसमिति बैठक को संबोधित','Addressed the extended State Executive meeting and Yuva Samvad in Andhra Pradesh.','आंध्र प्रदेश में विस्तारित प्रदेश कार्यसमिति बैठक और युवा संवाद को संबोधित किया।','Visakhapatnam, Andhra Pradesh','विशाखापत्तनम, आंध्र प्रदेश','https://www.nitinnabin.com/images/albums/album-3.jpg',1),
('2026-08-17','Public event','सार्वजनिक कार्यक्रम','Attended the launch of M. Venkaiah Naidu''s biography','एम. वेंकैया नायडू की जीवनी के विमोचन में सम्मिलित','Present at the launch of the biography of former Vice President M. Venkaiah Naidu.','पूर्व उपराष्ट्रपति एम. वेंकैया नायडू की जीवनी के विमोचन कार्यक्रम में उपस्थित।','New Delhi','नई दिल्ली','https://www.nitinnabin.com/images/albums/album-4.jpg',2),
('2026-08-12','Event','कार्यक्रम','Joined the Tiranga Yatra','तिरंगा यात्रा कार्यक्रम में सम्मिलित','Took part in the Tiranga Yatra held in the capital.','राजधानी में आयोजित तिरंगा यात्रा कार्यक्रम में भाग लिया।','New Delhi','नई दिल्ली','https://www.nitinnabin.com/images/albums/album-5.jpg',3),
('2026-04-06','Statement','वक्तव्य','Addressed workers on the party''s 47th Foundation Day','पार्टी के 47वें स्थापना दिवस पर कार्यकर्ताओं को संबोधित','Said the party''s strength rests on the dedication of its lakhs of workers, and paid tribute to past national presidents. Noted the party was founded in 1980.','कहा कि पार्टी की शक्ति उसके लाखों कार्यकर्ताओं के समर्पण और निष्ठा पर टिकी है, और पूर्व राष्ट्रीय अध्यक्षों को श्रद्धांजलि दी।','New Delhi','नई दिल्ली','https://www.nitinnabin.com/images/albums/album-6.jpg',4);

-- Milestones (journey) ----------------------------------------------------
insert into public.milestones (year, kind_en, kind_hi, title_en, title_hi, place_en, place_hi, body_en, body_hi, record_en, record_hi, sort_order) values
('2006','Election','चुनाव','Elected to the Bihar Assembly at twenty-six','छब्बीस वर्ष की आयु में बिहार विधानसभा के लिए निर्वाचित','Patna West · Bihar','पटना पश्चिम · बिहार','Fielded in the by-election for Patna West, left vacant by the passing of his father, four-term MLA Nabin Kishore Prasad Sinha. Won by roughly 60,000 votes.','उसी क्षेत्र से चार बार विधायक रहे उनके पिता नवीन किशोर प्रसाद सिन्हा के निधन से रिक्त हुई पटना पश्चिम सीट पर उपचुनाव में उम्मीदवार बनाए गए। लगभग 60,000 मतों के अंतर से जीत दर्ज की।','Term: 11 May 2006 – 24 Nov 2010','कार्यकाल: 11 मई 2006 – 24 नव 2010',1),
('2010','Election','चुनाव','First win from Bankipur','बांकीपुर से पहली जीत','Bankipur · Patna','बांकीपुर · पटना','After delimitation, Patna West was reconstituted as Bankipur. Contested the new seat and won.','परिसीमन के बाद पटना पश्चिम का पुनर्गठन बांकीपुर के रूप में हुआ। नई सीट से चुनाव लड़ा और जीता।','Term: 2010 – 2015','कार्यकाल: 2010 – 2015',2),
('2015','Election','चुनाव','Third Assembly term','तीसरा विधानसभा कार्यकाल','Bankipur · Patna','बांकीपुर · पटना','Elected for a third consecutive term from Bankipur.','बांकीपुर से लगातार तीसरी बार निर्वाचित।','Term: 2015 – 2020','कार्यकाल: 2015 – 2020',3),
('2019','Organisation','संगठन','Yuva Morcha leadership','युवा मोर्चा नेतृत्व','Bihar · National','बिहार · राष्ट्रीय','Served as Bihar state president of the BJYM, later national general secretary of the Yuva Morcha.','भाजयुमो के बिहार प्रदेश अध्यक्ष, फिर युवा मोर्चा के राष्ट्रीय महामंत्री।','Organisational post','संगठनात्मक पद',4),
('2020','Election','चुनाव','Bankipur, fourth term','बांकीपुर, चौथा कार्यकाल','Bankipur · Patna','बांकीपुर · पटना','Won a fourth consecutive term by a margin of 39,036 votes.','39,036 मतों के अंतर से लगातार चौथी जीत।','Term: 2020 – 2025','कार्यकाल: 2020 – 2025',5),
('2021','Governance','शासन','Joined the cabinet','मंत्रिमंडल में प्रवेश','Government of Bihar','बिहार सरकार','Sworn in as Minister for Road Construction in the Nitish Kumar government.','नीतीश कुमार सरकार में पथ निर्माण मंत्री के रूप में शपथ।','Feb 2021 – Aug 2022','फ़र 2021 – अग 2022',6),
('2023','Organisation','संगठन','Chhattisgarh campaign','छत्तीसगढ़ अभियान','Chhattisgarh','छत्तीसगढ़','Appointed election in-charge for the Chhattisgarh Assembly election and led the party campaign.','छत्तीसगढ़ विधानसभा चुनाव के प्रभारी नियुक्त; पार्टी अभियान का नेतृत्व।','Election in-charge, 2023','चुनाव प्रभारी, 2023',7),
('2024','Governance','शासन','Back in cabinet','मंत्रिमंडल में वापसी','Government of Bihar','बिहार सरकार','Returned as Minister for Law & Justice, then took Urban Development & Housing and Road Construction.','विधि एवं न्याय मंत्री के रूप में वापसी, फिर नगर विकास एवं आवास तथा पथ निर्माण विभाग।','Mar 2024 – Dec 2025','मार्च 2024 – दिस 2025',8),
('2025','Election · National','चुनाव · राष्ट्रीय','Fifth term; Working President','पाँचवाँ कार्यकाल; कार्यकारी अध्यक्ष','Bankipur · New Delhi','बांकीपुर · नई दिल्ली','Polled 98,299 votes, winning by 51,936. In December the Parliamentary Board appointed him National Working President; he resigned from the Bihar cabinet.','98,299 मत, 51,936 के अंतर से जीत। दिसंबर में संसदीय बोर्ड ने राष्ट्रीय कार्यकारी अध्यक्ष नियुक्त किया; बिहार मंत्रिमंडल से इस्तीफा।','Dec 2025 – Jan 2026','दिस 2025 – जन 2026',9),
('2026','National','राष्ट्रीय','Elected National President','राष्ट्रीय अध्यक्ष निर्वाचित','Party headquarters · New Delhi','पार्टी मुख्यालय · नई दिल्ली','Elected unopposed on 20 January 2026 — the youngest to hold the post and the first from Bihar.','20 जनवरी 2026 को निर्विरोध निर्वाचित — इस पद पर सबसे युवा और बिहार से पहले।','National President, since 20 Jan 2026','राष्ट्रीय अध्यक्ष, 20 जन 2026 से',10);

-- Speeches ------------------------------------------------------------------
insert into public.speeches (event_date, kind_en, kind_hi, title_en, title_hi, venue_en, venue_hi, sort_order) values
('2026-08-18','Organisation','संगठन','Yuva Samvad','युवा संवाद','Visakhapatnam','विशाखापत्तनम',1),
('2026-08-18','Organisation','संगठन','Extended State Executive meeting','विस्तारित प्रदेश कार्यसमिति बैठक','Visakhapatnam','विशाखापत्तनम',2),
('2026-04-06','Foundation Day','स्थापना दिवस','Address on the party''s 47th Foundation Day','पार्टी के 47वें स्थापना दिवस पर संबोधन','New Delhi','नई दिल्ली',3),
('2026-02-21','Organisation','संगठन','Gujarat state organisational meeting','गुजरात प्रदेश संगठनात्मक बैठक को संबोधन','Gandhinagar','गांधीनगर',4);

-- Gallery -------------------------------------------------------------------
insert into public.gallery (image_url, caption_en, caption_hi, sub_en, sub_hi, sort_order) values
('https://www.nitinnabin.com/images/albums/album-1.jpg','Taking charge','कार्यभार ग्रहण','New Delhi · 2026','नई दिल्ली · 2026',1),
('https://www.nitinnabin.com/images/albums/album-2.jpg','Bihar','बिहार','Bankipur & Patna','बांकीपुर एवं पटना',2),
('https://www.nitinnabin.com/images/albums/album-3.jpg','Organisation','संगठन','State visits','राज्य दौरे',3),
('https://www.nitinnabin.com/images/albums/album-4.jpg','National events','राष्ट्रीय कार्यक्रम','2026','2026',4),
('https://www.nitinnabin.com/images/albums/album-5.jpg','Public meetings','जनसभाएँ','Content awaited','सामग्री प्रतीक्षित',5),
('https://www.nitinnabin.com/images/albums/album-6.jpg','Speeches','भाषण','Content awaited','सामग्री प्रतीक्षित',6);

-- Social posts --------------------------------------------------------------
insert into public.social_posts (platform, image_url, text_en, text_hi, label_en, label_hi, when_en, when_hi, stats, sort_order) values
('fb','https://www.nitinnabin.com/images/portrait-bio.avif','Joined the extended State Executive meeting and Yuva Samvad in Visakhapatnam, Andhra Pradesh, and interacted with energetic party workers.','आंध्र प्रदेश के विशाखापत्तनम में आयोजित विस्तारित प्रदेश कार्यसमिति बैठक व युवा संवाद में सम्मिलित होकर ऊर्जावान कार्यकर्ताओं से संवाद किया।','Facebook Video','Facebook Video','18 Aug 2026','18 अग 2026','👍 4.8K',1),
('fb','https://www.nitinnabin.com/images/portrait-fields.avif','Took part in the Tiranga Yatra in New Delhi. Renewed the Nation First pledge with lakhs of workers.','राजधानी नई दिल्ली में आयोजित तिरंगा यात्रा कार्यक्रम में भाग लिया। लाखों कार्यकर्ताओं के साथ राष्ट्र प्रथम का संकल्प दोहराया।','Tiranga Yatra','तिरंगा यात्रा','12 Aug 2026','12 अग 2026','👍 6.5K',2),
('fb','https://www.nitinnabin.com/images/portrait-contact.avif','Attended the launch of the inspiring biography of former Vice President Shri M. Venkaiah Naidu. His public life is a guide for all of us.','पूर्व उपराष्ट्रपति श्री एम. वेंकैया नायडू जी की प्रेरक जीवनी के विमोचन कार्यक्रम में सहभागिता। उनका सार्वजनिक जीवन हम सभी के लिए पथप्रदर्शक है।','New Delhi','नई दिल्ली','17 Aug 2026','17 अग 2026','👍 3.9K',3),
('x','https://www.nitinnabin.com/images/portrait-fields.avif','Heartfelt greetings to every dedicated karyakarta on the party''s 47th Foundation Day. The party''s strength rests on the dedication and commitment of lakhs of workers. #BJPFoundationDay','पार्टी के 47वें स्थापना दिवस पर समस्त कर्मठ कार्यकर्ताओं को हार्दिक बधाई। पार्टी की शक्ति लाखों कार्यकर्ताओं के समर्पण और निष्ठा पर टिकी है। #BJPFoundationDay','Foundation Day message','स्थापना दिवस संदेश','06 Apr 2026','06 अप्रैल 2026','🔁 1.8K ❤️ 9.4K',1),
('x','https://www.nitinnabin.com/images/portrait-bio.avif','Organisational meeting with senior office-bearers of the Gujarat unit at Kamalam, Gandhinagar. Urged workers to stay active with new goals.','कमलम, गांधीनगर में गुजरात प्रदेश संगठन के वरिष्ठ पदाधिकारियों के साथ सांगठनिक बैठक। कार्यकर्ताओं को नए लक्ष्यों के साथ निरंतर सक्रिय रहने का आह्वान किया।','Gandhinagar, Gujarat','गांधीनगर, गुजरात प्रवास','21 Feb 2026','21 फ़र 2026','🔁 2.3K ❤️ 11.8K',2),
('x','https://www.nitinnabin.com/images/hero-bg.jpg','First official visit to West Bengal: state core team meeting in Durgapur and the Bardhaman division workers'' convention. The enthusiasm is unprecedented.','पश्चिम बंगाल का पहला आधिकारिक दौरा: दुर्गापुर में प्रदेश कोर टीम बैठक एवं बर्दवान संभाग कार्यकर्ता सम्मेलन में भाग लिया। कार्यकर्ताओं का उत्साह अभूतपूर्व है।','West Bengal visit','पश्चिम बंगाल प्रवास','27 Jan 2026','27 जन 2026','🔁 1.9K ❤️ 8.6K',3),
('ig','https://www.nitinnabin.com/images/portrait-bio.avif','Shared thoughts with young people at the Yuva Samvad in Visakhapatnam. Innovation and service to the nation are India''s future. ✨','विशाखापत्तनम में आयोजित युवा संवाद में युवाओं के साथ प्रेरक विचार साझा किए। नवाचार और राष्ट्रसेवा ही भारत का भविष्य है। ✨','Visakhapatnam • Yuva Samvad','विशाखापत्तनम • युवा संवाद','3 days ago','3 दिन पहले','❤️ 14.8K · 💬 482',1),
('ig','https://www.nitinnabin.com/images/portrait-fields.avif','Sangathan Parv: the energy and dedication of karyakartas is the party''s real capital. Service is organisation.','संगठन पर्व: कार्यकर्ताओं की ऊर्जा और समर्पण ही भारतीय जनता पार्टी की वास्तविक पूंजी है। सेवा ही संगठन।','Kamalam • Organisation review','कमलम • संगठन समीक्षा','5 days ago','5 दिन पहले','❤️ 19.2K · 💬 640',2),
('ig','https://www.nitinnabin.com/images/portrait-contact.avif','Warm interaction with workers and senior office-bearers at the central office in New Delhi.','नई दिल्ली स्थित केंद्रीय कार्यालय में कार्यकर्ताओं एवं वरिष्ठ पदाधिकारियों से आत्मीय संवाद।','New Delhi • Central office','नई दिल्ली • केंद्रीय कार्यालय','1 week ago','1 सप्ताह पहले','❤️ 12.1K · 💬 310',3),
('yt','https://www.nitinnabin.com/images/portrait-bio.avif','Taking charge: historic address as National President | New Delhi','कार्यभार ग्रहण: राष्ट्रीय अध्यक्ष के रूप में ऐतिहासिक संबोधन | नई दिल्ली','18:42','18:42','1 month ago','1 माह पहले','94K views',1),
('yt','https://www.nitinnabin.com/images/portrait-fields.avif','Inspiring message to party workers on the 47th Foundation Day','47वें स्थापना दिवस पर पार्टी कार्यकर्ताओं को प्रेरणादायी संदेश','14:15','14:15','2 weeks ago','2 सप्ताह पहले','128K views',2),
('yt','https://www.nitinnabin.com/images/portrait-contact.avif','Extended State Executive meeting: key organisational address','विस्तारित प्रदेश कार्यसमिति बैठक: महत्वपूर्ण सांगठनिक संबोधन','22:08','22:08','3 weeks ago','3 सप्ताह पहले','76K views',3);
