// Fallback content. Used when Supabase env vars are missing, a table is empty,
// or a query fails — so the site always renders. Keep in sync with supabase/seed.sql.
import type { GalleryItem, Milestone, SocialPost, Speech, Update } from "./types";

const IMG = "https://www.nitinnabin.com/images";

export const seedUpdates: Update[] = [
  { id: "u1", event_date: "2026-08-18", kind_en: "Event", kind_hi: "कार्यक्रम", title_en: "Addressed the extended State Executive meeting", title_hi: "विस्तारित प्रदेश कार्यसमिति बैठक को संबोधित", summary_en: "Addressed the extended State Executive meeting and Yuva Samvad in Andhra Pradesh.", summary_hi: "आंध्र प्रदेश में विस्तारित प्रदेश कार्यसमिति बैठक और युवा संवाद को संबोधित किया।", place_en: "Visakhapatnam, Andhra Pradesh", place_hi: "विशाखापत्तनम, आंध्र प्रदेश", image_url: `${IMG}/albums/album-3.jpg`, sort_order: 1 },
  { id: "u2", event_date: "2026-08-17", kind_en: "Public event", kind_hi: "सार्वजनिक कार्यक्रम", title_en: "Attended the launch of M. Venkaiah Naidu's biography", title_hi: "एम. वेंकैया नायडू की जीवनी के विमोचन में सम्मिलित", summary_en: "Present at the launch of the biography of former Vice President M. Venkaiah Naidu.", summary_hi: "पूर्व उपराष्ट्रपति एम. वेंकैया नायडू की जीवनी के विमोचन कार्यक्रम में उपस्थित।", place_en: "New Delhi", place_hi: "नई दिल्ली", image_url: `${IMG}/albums/album-4.jpg`, sort_order: 2 },
  { id: "u3", event_date: "2026-08-12", kind_en: "Event", kind_hi: "कार्यक्रम", title_en: "Joined the Tiranga Yatra", title_hi: "तिरंगा यात्रा कार्यक्रम में सम्मिलित", summary_en: "Took part in the Tiranga Yatra held in the capital.", summary_hi: "राजधानी में आयोजित तिरंगा यात्रा कार्यक्रम में भाग लिया।", place_en: "New Delhi", place_hi: "नई दिल्ली", image_url: `${IMG}/albums/album-5.jpg`, sort_order: 3 },
  { id: "u4", event_date: "2026-04-06", kind_en: "Statement", kind_hi: "वक्तव्य", title_en: "Addressed workers on the party's 47th Foundation Day", title_hi: "पार्टी के 47वें स्थापना दिवस पर कार्यकर्ताओं को संबोधित", summary_en: "Said the party's strength rests on the dedication of its lakhs of workers, and paid tribute to past national presidents. Noted the party was founded in 1980.", summary_hi: "कहा कि पार्टी की शक्ति उसके लाखों कार्यकर्ताओं के समर्पण और निष्ठा पर टिकी है, और पूर्व राष्ट्रीय अध्यक्षों को श्रद्धांजलि दी।", place_en: "New Delhi", place_hi: "नई दिल्ली", image_url: `${IMG}/albums/album-6.jpg`, sort_order: 4 },
];

export const seedMilestones: Milestone[] = [
  { id: "m1", year: "2006", kind_en: "Election", kind_hi: "चुनाव", title_en: "Elected to the Bihar Assembly at twenty-six", title_hi: "छब्बीस वर्ष की आयु में बिहार विधानसभा के लिए निर्वाचित", place_en: "Patna West · Bihar", place_hi: "पटना पश्चिम · बिहार", body_en: "Fielded in the by-election for Patna West, left vacant by the passing of his father, four-term MLA Nabin Kishore Prasad Sinha. Won by roughly 60,000 votes.", body_hi: "उसी क्षेत्र से चार बार विधायक रहे उनके पिता नवीन किशोर प्रसाद सिन्हा के निधन से रिक्त हुई पटना पश्चिम सीट पर उपचुनाव में उम्मीदवार बनाए गए। लगभग 60,000 मतों के अंतर से जीत दर्ज की।", record_en: "Term: 11 May 2006 – 24 Nov 2010", record_hi: "कार्यकाल: 11 मई 2006 – 24 नव 2010", sort_order: 1 },
  { id: "m2", year: "2010", kind_en: "Election", kind_hi: "चुनाव", title_en: "First win from Bankipur", title_hi: "बांकीपुर से पहली जीत", place_en: "Bankipur · Patna", place_hi: "बांकीपुर · पटना", body_en: "After delimitation, Patna West was reconstituted as Bankipur. Contested the new seat and won.", body_hi: "परिसीमन के बाद पटना पश्चिम का पुनर्गठन बांकीपुर के रूप में हुआ। नई सीट से चुनाव लड़ा और जीता।", record_en: "Term: 2010 – 2015", record_hi: "कार्यकाल: 2010 – 2015", sort_order: 2 },
  { id: "m3", year: "2015", kind_en: "Election", kind_hi: "चुनाव", title_en: "Third Assembly term", title_hi: "तीसरा विधानसभा कार्यकाल", place_en: "Bankipur · Patna", place_hi: "बांकीपुर · पटना", body_en: "Elected for a third consecutive term from Bankipur.", body_hi: "बांकीपुर से लगातार तीसरी बार निर्वाचित।", record_en: "Term: 2015 – 2020", record_hi: "कार्यकाल: 2015 – 2020", sort_order: 3 },
  { id: "m4", year: "2019", kind_en: "Organisation", kind_hi: "संगठन", title_en: "Yuva Morcha leadership", title_hi: "युवा मोर्चा नेतृत्व", place_en: "Bihar · National", place_hi: "बिहार · राष्ट्रीय", body_en: "Served as Bihar state president of the BJYM, later national general secretary of the Yuva Morcha.", body_hi: "भाजयुमो के बिहार प्रदेश अध्यक्ष, फिर युवा मोर्चा के राष्ट्रीय महामंत्री।", record_en: "Organisational post", record_hi: "संगठनात्मक पद", sort_order: 4 },
  { id: "m5", year: "2020", kind_en: "Election", kind_hi: "चुनाव", title_en: "Bankipur, fourth term", title_hi: "बांकीपुर, चौथा कार्यकाल", place_en: "Bankipur · Patna", place_hi: "बांकीपुर · पटना", body_en: "Won a fourth consecutive term by a margin of 39,036 votes.", body_hi: "39,036 मतों के अंतर से लगातार चौथी जीत।", record_en: "Term: 2020 – 2025", record_hi: "कार्यकाल: 2020 – 2025", sort_order: 5 },
  { id: "m6", year: "2021", kind_en: "Governance", kind_hi: "शासन", title_en: "Joined the cabinet", title_hi: "मंत्रिमंडल में प्रवेश", place_en: "Government of Bihar", place_hi: "बिहार सरकार", body_en: "Sworn in as Minister for Road Construction in the Nitish Kumar government.", body_hi: "नीतीश कुमार सरकार में पथ निर्माण मंत्री के रूप में शपथ।", record_en: "Feb 2021 – Aug 2022", record_hi: "फ़र 2021 – अग 2022", sort_order: 6 },
  { id: "m7", year: "2023", kind_en: "Organisation", kind_hi: "संगठन", title_en: "Chhattisgarh campaign", title_hi: "छत्तीसगढ़ अभियान", place_en: "Chhattisgarh", place_hi: "छत्तीसगढ़", body_en: "Appointed election in-charge for the Chhattisgarh Assembly election and led the party campaign.", body_hi: "छत्तीसगढ़ विधानसभा चुनाव के प्रभारी नियुक्त; पार्टी अभियान का नेतृत्व।", record_en: "Election in-charge, 2023", record_hi: "चुनाव प्रभारी, 2023", sort_order: 7 },
  { id: "m8", year: "2024", kind_en: "Governance", kind_hi: "शासन", title_en: "Back in cabinet", title_hi: "मंत्रिमंडल में वापसी", place_en: "Government of Bihar", place_hi: "बिहार सरकार", body_en: "Returned as Minister for Law & Justice, then took Urban Development & Housing and Road Construction.", body_hi: "विधि एवं न्याय मंत्री के रूप में वापसी, फिर नगर विकास एवं आवास तथा पथ निर्माण विभाग।", record_en: "Mar 2024 – Dec 2025", record_hi: "मार्च 2024 – दिस 2025", sort_order: 8 },
  { id: "m9", year: "2025", kind_en: "Election · National", kind_hi: "चुनाव · राष्ट्रीय", title_en: "Fifth term; Working President", title_hi: "पाँचवाँ कार्यकाल; कार्यकारी अध्यक्ष", place_en: "Bankipur · New Delhi", place_hi: "बांकीपुर · नई दिल्ली", body_en: "Polled 98,299 votes, winning by 51,936. In December the Parliamentary Board appointed him National Working President; he resigned from the Bihar cabinet.", body_hi: "98,299 मत, 51,936 के अंतर से जीत। दिसंबर में संसदीय बोर्ड ने राष्ट्रीय कार्यकारी अध्यक्ष नियुक्त किया; बिहार मंत्रिमंडल से इस्तीफा।", record_en: "Dec 2025 – Jan 2026", record_hi: "दिस 2025 – जन 2026", sort_order: 9 },
  { id: "m10", year: "2026", kind_en: "National", kind_hi: "राष्ट्रीय", title_en: "Elected National President", title_hi: "राष्ट्रीय अध्यक्ष निर्वाचित", place_en: "Party headquarters · New Delhi", place_hi: "पार्टी मुख्यालय · नई दिल्ली", body_en: "Elected unopposed on 20 January 2026 — the youngest to hold the post and the first from Bihar.", body_hi: "20 जनवरी 2026 को निर्विरोध निर्वाचित — इस पद पर सबसे युवा और बिहार से पहले।", record_en: "National President, since 20 Jan 2026", record_hi: "राष्ट्रीय अध्यक्ष, 20 जन 2026 से", sort_order: 10 },
];

export const seedSpeeches: Speech[] = [
  { id: "sp1", event_date: "2026-08-18", kind_en: "Organisation", kind_hi: "संगठन", title_en: "Yuva Samvad", title_hi: "युवा संवाद", venue_en: "Visakhapatnam", venue_hi: "विशाखापत्तनम", video_url: null, sort_order: 1 },
  { id: "sp2", event_date: "2026-08-18", kind_en: "Organisation", kind_hi: "संगठन", title_en: "Extended State Executive meeting", title_hi: "विस्तारित प्रदेश कार्यसमिति बैठक", venue_en: "Visakhapatnam", venue_hi: "विशाखापत्तनम", video_url: null, sort_order: 2 },
  { id: "sp3", event_date: "2026-04-06", kind_en: "Foundation Day", kind_hi: "स्थापना दिवस", title_en: "Address on the party's 47th Foundation Day", title_hi: "पार्टी के 47वें स्थापना दिवस पर संबोधन", venue_en: "New Delhi", venue_hi: "नई दिल्ली", video_url: null, sort_order: 3 },
  { id: "sp4", event_date: "2026-02-21", kind_en: "Organisation", kind_hi: "संगठन", title_en: "Gujarat state organisational meeting", title_hi: "गुजरात प्रदेश संगठनात्मक बैठक को संबोधन", venue_en: "Gandhinagar", venue_hi: "गांधीनगर", video_url: null, sort_order: 4 },
];

export const seedGallery: GalleryItem[] = [
  { id: "g1", image_url: `${IMG}/albums/album-1.jpg`, caption_en: "Taking charge", caption_hi: "कार्यभार ग्रहण", sub_en: "New Delhi · 2026", sub_hi: "नई दिल्ली · 2026", sort_order: 1 },
  { id: "g2", image_url: `${IMG}/albums/album-2.jpg`, caption_en: "Bihar", caption_hi: "बिहार", sub_en: "Bankipur & Patna", sub_hi: "बांकीपुर एवं पटना", sort_order: 2 },
  { id: "g3", image_url: `${IMG}/albums/album-3.jpg`, caption_en: "Organisation", caption_hi: "संगठन", sub_en: "State visits", sub_hi: "राज्य दौरे", sort_order: 3 },
  { id: "g4", image_url: `${IMG}/albums/album-4.jpg`, caption_en: "National events", caption_hi: "राष्ट्रीय कार्यक्रम", sub_en: "2026", sub_hi: "2026", sort_order: 4 },
  { id: "g5", image_url: `${IMG}/albums/album-5.jpg`, caption_en: "Public meetings", caption_hi: "जनसभाएँ", sub_en: "Content awaited", sub_hi: "सामग्री प्रतीक्षित", sort_order: 5 },
  { id: "g6", image_url: `${IMG}/albums/album-6.jpg`, caption_en: "Speeches", caption_hi: "भाषण", sub_en: "Content awaited", sub_hi: "सामग्री प्रतीक्षित", sort_order: 6 },
];

export const seedSocial: SocialPost[] = [
  // Facebook (https://www.facebook.com/NitinNabinBJP/)
  {
    id: "s-fb-temple",
    platform: "fb",
    image_url: "/api/social-media/temple",
    text_en: "सर्वमङ्गलमाङ्गल्ये शिवे सर्वार्थसाधिके। शरण्ये त्र्यम्बके गौरि नारायणि नमोऽस्तु ते॥ Performed sacred temple prayers and morning darshan, seeking divine blessings of peace, health and prosperity for all 140 crore countrymen. Jai Maa Bhavani! 🚩🙏",
    text_hi: "सर्वमङ्गलमाङ्गल्ये शिवे सर्वार्थसाधिके। शरण्ये त्र्यम्बके गौरि नारायणि नमोऽस्तु ते॥ माँ भगवती के पावन दर्शन एवं पूजन कर समस्त देशवासियों के सुख, शांति, समृद्धि एवं आरोग्य की मंगल कामना की। जय माँ भवानी! 🚩🙏",
    label_en: "Temple Darshan & Prayers",
    label_hi: "माँ भगवती दर्शन एवं पूजन",
    when_en: "11m ago",
    when_hi: "11 मिनट पहले",
    stats: "👍 4.8K · 💬 412 · 🔄 230",
    post_url: "https://www.facebook.com/NitinNabinBJP/",
    sort_order: 1,
  },
  {
    id: "s-fb-1",
    platform: "fb",
    image_url: "https://i.ytimg.com/vi/xKYhZObZdNc/hq720.jpg",
    text_en: "Rudrapur, Uttarakhand: Participated in the massive Punjabi Gaurav Sammelan alongside Hon'ble Chief Minister Shri Pushkar Singh Dhami Ji. The Sikh and Punjabi community's courage, patriotism and sacrifices are the greatest inspiration for our nation.",
    text_hi: "रुद्रपुर, उत्तराखंड: माननीय मुख्यमंत्री श्री पुष्कर सिंह धामी जी के साथ भव्य 'पंजाबी गौरव सम्मेलन' में सहभागिता। सिख एवं पंजाबी समाज का अदम्य शौर्य, राष्ट्रभक्ति और बलिदान संपूर्ण देश के लिए सर्वोच्च प्रेरणा है।",
    label_en: "Punjabi Gaurav Sammelan",
    label_hi: "पंजाबी गौरव सम्मेलन",
    when_en: "09 Sep 2026",
    when_hi: "09 सित 2026",
    stats: "👍 14.8K · 💬 1.1K",
    post_url: "https://www.facebook.com/NitinNabinBJP/",
    sort_order: 2,
  },
  {
    id: "s-fb-2",
    platform: "fb",
    image_url: "https://i.ytimg.com/vi/bRmYiNLjikM/hq720.jpg",
    text_en: "Announced the nationwide 'Seva Sankalp Abhiyan' (17 September to 17 October) commemorating Hon'ble Prime Minister Shri Narendra Modi Ji's 25 years of dedicated service to the nation. Lakhs of party workers will undertake service initiatives across India.",
    text_hi: "आदरणीय प्रधानमंत्री श्री नरेंद्र मोदी जी के जनसेवा के 25 गौरवशाली वर्ष पूर्ण होने के उपलक्ष्य में 17 सितंबर से 17 अक्टूबर तक राष्ट्रव्यापी 'सेवा संकल्प अभियान' की घोषणा। लाखों कार्यकर्ता देश भर में सेवा कार्यों से जुड़ेंगे।",
    label_en: "Seva Sankalp Abhiyan",
    label_hi: "सेवा संकल्प अभियान",
    when_en: "09 Sep 2026",
    when_hi: "09 सित 2026",
    stats: "👍 18.2K · 💬 1.4K",
    post_url: "https://www.facebook.com/NitinNabinBJP/",
    sort_order: 2,
  },
  {
    id: "s-fb-3",
    platform: "fb",
    image_url: "https://i.ytimg.com/vi/7K3V1o9SA1Y/hq720.jpg",
    text_en: "Addressed the Ex-Servicemen Sammelan and interacted with youth in Haldwani, Uttarakhand. Urged youth to become job creators and pioneers of innovation in the journey toward Viksit Bharat.",
    text_hi: "हल्द्वानी, उत्तराखंड में पूर्व सैनिक सम्मेलन को संबोधित किया एवं युवाओं से संवाद। विकसित भारत के निर्माण में युवाओं से 'जॉब सीकर' नहीं बल्कि 'जॉब क्रिएटर' और नवाचार का प्रणेता बनने का आह्वान किया।",
    label_en: "Haldwani Convention",
    label_hi: "हल्द्वानी सम्मेलन",
    when_en: "08 Sep 2026",
    when_hi: "08 सित 2026",
    stats: "👍 12.6K · 💬 890",
    post_url: "https://www.facebook.com/NitinNabinBJP/",
    sort_order: 3,
  },
  {
    id: "s-fb-4",
    platform: "fb",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Nitin_Nabin%2C_National_President_of_Bharatiya_Janata_Party_meeting_with_the_President_of_India%2C_Droupadi_Murmu_at_Rashtrapati_Bhavan_%282025%29.jpg/1280px-Nitin_Nabin%2C_National_President_of_Bharatiya_Janata_Party_meeting_with_the_President_of_India%2C_Droupadi_Murmu_at_Rashtrapati_Bhavan_%282025%29.jpg",
    text_en: "Had the privilege of calling on the Hon'ble President of India, Smt. Droupadi Murmu Ji at Rashtrapati Bhavan, New Delhi. Received her kind guidance and blessings.",
    text_hi: "राष्ट्रपति भवन, नई दिल्ली में माननीय राष्ट्रपति श्रीमती द्रौपदी मुर्मू जी से शिष्टाचार भेंट करने का सौभाग्य प्राप्त हुआ। उनका आत्मीय मार्गदर्शन एवं आशीर्वाद प्राप्त किया।",
    label_en: "Rashtrapati Bhavan",
    label_hi: "राष्ट्रपति भवन भेंट",
    when_en: "02 Sep 2026",
    when_hi: "02 सित 2026",
    stats: "👍 22.4K · 💬 1.8K",
    post_url: "https://www.facebook.com/NitinNabinBJP/",
    sort_order: 4,
  },
  {
    id: "s-fb-5",
    platform: "fb",
    image_url: "https://i.ytimg.com/vi/5Mn1YXcmYAM/hq720_2.jpg",
    text_en: "Yuva Samvad in Uttarakhand: Vibrant exchange of ideas with college students and aspiring entrepreneurs. India's youth are the foundational pillars of self-reliant Bharat.",
    text_hi: "उत्तराखंड में युवा संवाद: कॉलेज विद्यार्थियों और युवा उद्यमियों के साथ विचारों का प्रेरक आदान-प्रदान। भारत की युवा शक्ति आत्मनिर्भर भारत का मजबूत आधार स्तंभ है।",
    label_en: "Yuva Samvad Dialogue",
    label_hi: "युवा संवाद कार्यक्रम",
    when_en: "08 Sep 2026",
    when_hi: "08 सित 2026",
    stats: "👍 26.1K · 💬 2.3K",
    post_url: "https://www.facebook.com/NitinNabinBJP/",
    sort_order: 5,
  },
  {
    id: "s-fb-6",
    platform: "fb",
    image_url: "https://i.ytimg.com/vi/gYFcMYIWXjE/hq720.jpg",
    text_en: "Unveiled the new National Organizational Team of the Bharatiya Janata Party at Central Headquarters, New Delhi. Strengthened leadership to empower grassroots workers across every state.",
    text_hi: "केंद्रीय मुख्यालय, नई दिल्ली में भारतीय जनता पार्टी की नई राष्ट्रीय संगठनात्मक टीम की घोषणा। हर राज्य में बूथ स्तर तक संगठन को नई ऊर्जा देने का संकल्प।",
    label_en: "National Team Announcement",
    label_hi: "राष्ट्रीय टीम घोषणा",
    when_en: "17 Aug 2026",
    when_hi: "17 अग 2026",
    stats: "👍 31.5K · 💬 3.1K",
    post_url: "https://www.facebook.com/NitinNabinBJP/",
    sort_order: 6,
  },
  {
    id: "s-fb-7",
    platform: "fb",
    image_url: "https://i.ytimg.com/vi/BOx2eeNKgSA/hq720.jpg",
    text_en: "National interview addressing public welfare initiatives, urban governance reforms and organizational expansion ahead of upcoming state and national milestones.",
    text_hi: "राष्ट्रीय साक्षात्कार: जन कल्याणकारी योजनाओं, नगरीय प्रशासन सुधारों एवं आगामी राष्ट्रीय लक्ष्यों पर संगठन के विस्तार पर विस्तृत संवाद।",
    label_en: "National Media Briefing",
    label_hi: "राष्ट्रीय मीडिया संवाद",
    when_en: "17 Aug 2026",
    when_hi: "17 अग 2026",
    stats: "👍 15.9K · 💬 940",
    post_url: "https://www.facebook.com/NitinNabinBJP/",
    sort_order: 7,
  },
  {
    id: "s-fb-8",
    platform: "fb",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Nitish_Kumar_inaugurating_JP_path_of_Ganga_Path.jpg/1280px-Nitish_Kumar_inaugurating_JP_path_of_Ganga_Path.jpg",
    text_en: "Key infrastructure development: Dedicated modern roads and elevated connectivity projects including JP Ganga Path to the citizens of Patna, ensuring seamless urban transport.",
    text_hi: "महत्वपूर्ण बुनियादी ढाँचा विकास: जेपी गंगा पथ सहित आधुनिक सड़कों और एलिवेटेड कनेक्टिविटी परियोजनाओं से पटनावासियों को सुगम एवं निर्बाध यातायात की सौगात।",
    label_en: "Infrastructure Milestone",
    label_hi: "पथ निर्माण एवं विकास",
    when_en: "25 Jul 2026",
    when_hi: "25 जुल 2026",
    stats: "👍 19.3K · 💬 1.2K",
    post_url: "https://www.facebook.com/NitinNabinBJP/",
    sort_order: 8,
  },

  // X / Twitter (https://x.com/NitinNabin)
  {
    id: "s-x-temple",
    platform: "x",
    image_url: "/api/social-media/temple",
    text_en: "सर्वमङ्गलमाङ्गल्ये शिवे सर्वार्थसाधिके। शरण्ये त्र्यम्बके गौरि नारायणि नमोऽस्तु ते॥ Sacred temple darshan and prayers for the peace, progress and well-being of all countrymen. #JaiMaaBhavani #RashtraPratham 🚩🙏",
    text_hi: "सर्वमङ्गलमाङ्गल्ये शिवे सर्वार्थसाधिके। शरण्ये त्र्यम्बके गौरि नारायणि नमोऽस्तु ते॥ माँ भगवती के पावन दर्शन एवं पूजन कर समस्त देशवासियों के कल्याण एवं राष्ट्र की उन्नति की मंगल कामना की। #जय_माँ_भवानी 🚩🙏",
    label_en: "Temple Darshan",
    label_hi: "दर्शन एवं पूजन",
    when_en: "25m ago",
    when_hi: "25 मिनट पहले",
    stats: "🔁 1.8K ❤️ 9.2K",
    post_url: "https://x.com/NitinNabin",
    sort_order: 1,
  },
  {
    id: "s-x-1",
    platform: "x",
    image_url: "https://i.ytimg.com/vi/xKYhZObZdNc/hq720.jpg",
    text_en: "At Rudrapur, Uttarakhand: Paid glowing tributes to the Sikh community's immense sacrifices for Akhand Bharat at Punjabi Gaurav Sammelan. Under PM @narendramodi Ji, historic honor and justice have been delivered. #RashtraPratham",
    text_hi: "रुद्रपुर, उत्तराखंड: 'पंजाबी गौरव सम्मेलन' में अखंड भारत के लिए सिख समाज के अप्रतिम बलिदानों को नमन किया। पीएम @narendramodi जी के नेतृत्व में सिख समाज के मान-सम्मान और न्याय के लिए ऐतिहासिक कार्य हुए हैं। #राष्ट्रप्रथम",
    label_en: "Punjabi Gaurav Sammelan",
    label_hi: "पंजाबी गौरव सम्मेलन",
    when_en: "09 Sep 2026",
    when_hi: "09 सित 2026",
    stats: "🔁 4.2K ❤️ 18.5K",
    post_url: "https://x.com/NitinNabin",
    sort_order: 2,
  },
  {
    id: "s-x-2",
    platform: "x",
    image_url: "https://i.ytimg.com/vi/bRmYiNLjikM/hq720.jpg",
    text_en: "'Seva Sankalp Abhiyan' will be observed nationwide from 17 Sept to 17 Oct celebrating PM Shri @narendramodi Ji's 25 glorious years in public service. Dedicated to welfare of the poor and empowerment of the marginalized. #SevaSankalp",
    text_hi: "पीएम श्री @narendramodi जी के 25 गौरवशाली जनसेवा वर्षों के उपलक्ष्य में 17 सितंबर से 17 अक्टूबर तक देशव्यापी 'सेवा संकल्प अभियान' का आयोजन। गरीब कल्याण और वंचितों के उत्थान को समर्पित। #सेवा_संकल्प",
    label_en: "Seva Sankalp Abhiyan",
    label_hi: "सेवा संकल्प अभियान",
    when_en: "09 Sep 2026",
    when_hi: "09 सित 2026",
    stats: "🔁 6.8K ❤️ 27.3K",
    post_url: "https://x.com/NitinNabin",
    sort_order: 2,
  },
  {
    id: "s-x-3",
    platform: "x",
    image_url: "https://i.ytimg.com/vi/IZVtxEM8fPQ/hq720.jpg",
    text_en: "Vande Mataram is the divine anthem of India's freedom struggle that inspired millions to lay down their lives for the Motherland. Those who disrespect it disrespect the sacred soil of Bharat.",
    text_hi: "वंदे मातरम् माँ भारती की स्वतंत्रता का वह अमर मंत्र है जिसने लाखों हुतात्माओं को सर्वस्व अर्पण करने की प्रेरणा दी। इसका अनादर देश के शहीदों का अनादर है।",
    label_en: "Vande Mataram Statement",
    label_hi: "वंदे मातरम् वक्तव्य",
    when_en: "08 Sep 2026",
    when_hi: "08 सित 2026",
    stats: "🔁 5.1K ❤️ 21.4K",
    post_url: "https://x.com/NitinNabin",
    sort_order: 3,
  },
  {
    id: "s-x-4",
    platform: "x",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Nitin_Nabin%2C_National_President_of_Bharatiya_Janata_Party_meeting_with_the_President_of_India%2C_Droupadi_Murmu_at_Rashtrapati_Bhavan_%282025%29.jpg/1280px-Nitin_Nabin%2C_National_President_of_Bharatiya_Janata_Party_meeting_with_the_President_of_India%2C_Droupadi_Murmu_at_Rashtrapati_Bhavan_%282025%29.jpg",
    text_en: "Privileged to meet Hon'ble President Smt. Droupadi Murmu Ji at Rashtrapati Bhavan. Shared thoughts on nation-building, social harmony and party's vision for Viksit Bharat 2047.",
    text_hi: "राष्ट्रपति भवन में आदरणीय राष्ट्रपति श्रीमती द्रौपदी मुर्मू जी से शिष्टाचार भेंट। राष्ट्र निर्माण, सामाजिक समरसता और विकसित भारत 2047 के संकल्पों पर संवाद।",
    label_en: "Rashtrapati Bhavan Meeting",
    label_hi: "राष्ट्रपति भवन भेंट",
    when_en: "02 Sep 2026",
    when_hi: "02 सित 2026",
    stats: "🔁 7.9K ❤️ 34.2K",
    post_url: "https://x.com/NitinNabin",
    sort_order: 4,
  },
  {
    id: "s-x-5",
    platform: "x",
    image_url: "https://i.ytimg.com/vi/gYFcMYIWXjE/hq720.jpg",
    text_en: "Announced the new National Team of BJP office-bearers. Warm congratulations and best wishes to all colleagues as we dedicate ourselves to 140 crore countrymen. #SevaHiSangathan",
    text_hi: "भाजपा की नई राष्ट्रीय टीम के सभी नवनियुक्त पदाधिकारियों को हार्दिक बधाई एवं शुभकामनाएँ। 140 करोड़ देशवासियों की सेवा के संकल्प के साथ निरंतर गतिमान। #सेवा_ही_संगठन",
    label_en: "New National Team",
    label_hi: "नई राष्ट्रीय टीम",
    when_en: "17 Aug 2026",
    when_hi: "17 अग 2026",
    stats: "🔁 9.4K ❤️ 42.1K",
    post_url: "https://x.com/NitinNabin",
    sort_order: 5,
  },
  {
    id: "s-x-6",
    platform: "x",
    image_url: "https://i.ytimg.com/vi/PjeVmBTBQDs/hq720.jpg",
    text_en: "Inspiring interaction with GenZ innovators and college students in Haldwani alongside CM @pushkardhami Ji. Youths' innovative power will steer Viksit Bharat 2047! #YuvaShakti",
    text_hi: "हल्द्वानी में मुख्यमंत्री श्री @pushkardhami जी के साथ GenZ नवाचारियों और युवाओं से संवाद। युवाओं की ऊर्जा ही विकसित भारत 2047 का निर्माण करेगी! #युवा_शक्ति",
    label_en: "GenZ Youth Dialogue",
    label_hi: "GenZ युवा संवाद",
    when_en: "08 Sep 2026",
    when_hi: "08 सित 2026",
    stats: "🔁 8.3K ❤️ 36.8K",
    post_url: "https://x.com/NitinNabin",
    sort_order: 6,
  },
  {
    id: "s-x-7",
    platform: "x",
    image_url: "https://i.ytimg.com/vi/7K3V1o9SA1Y/hq720.jpg",
    text_en: "Salute to our brave ex-servicemen in Haldwani, Uttarakhand. Their selfless devotion to Bharat Mata is an eternal inspiration for every karyakarta. #JaiHind",
    text_hi: "हल्द्वानी, उत्तराखंड में वीर पूर्व सैनिकों को नमन। भारत माता की सेवा में उनका त्याग और समर्पण हर कार्यकर्ता के लिए सदैव प्रेरणादायी है। #जय_हिन्द",
    label_en: "Ex-Servicemen Sammelan",
    label_hi: "पूर्व सैनिक सम्मेलन",
    when_en: "08 Sep 2026",
    when_hi: "08 सित 2026",
    stats: "🔁 5.6K ❤️ 24.7K",
    post_url: "https://x.com/NitinNabin",
    sort_order: 7,
  },
  {
    id: "s-x-8",
    platform: "x",
    image_url: "https://i.ytimg.com/vi/5Mn1YXcmYAM/hq720_2.jpg",
    text_en: "Youth are not just job seekers, but the job creators of tomorrow. Energizing dialogue on technology, education and self-reliance in Uttarakhand.",
    text_hi: "युवा केवल रोजगार खोजने वाले नहीं, बल्कि भविष्य के रोजगार निर्माता हैं। तकनीकी नवाचार, शिक्षा और आत्मनिर्भरता पर उत्तराखंड में प्रेरक संवाद।",
    label_en: "Yuva Samvad Dialogue",
    label_hi: "युवा संवाद संवाद",
    when_en: "08 Sep 2026",
    when_hi: "08 सित 2026",
    stats: "🔁 6.2K ❤️ 28.9K",
    post_url: "https://x.com/NitinNabin",
    sort_order: 8,
  },

  // Instagram (https://www.instagram.com/nitinnabinbjp/)
  {
    id: "s-ig-temple",
    platform: "ig",
    image_url: "/api/social-media/temple",
    text_en: "सर्वमङ्गलमाङ्गल्ये शिवे सर्वार्थसाधिके। शरण्ये त्र्यम्बके गौरि नारायणि नमोऽस्तु ते॥ Divine morning temple darshan. May Maa Bhavani bless our motherland with peace, health and prosperity! 🚩✨🙏",
    text_hi: "सर्वमङ्गलमाङ्गल्ये शिवे सर्वार्थसाधिके। शरण्ये त्र्यम्बके गौरि नारायणि नमोऽस्तु ते॥ माँ जगदम्बे के पावन दर्शन एवं वंदन। जय माँ भवानी! 🚩✨🙏",
    label_en: "Temple Darshan",
    label_hi: "माँ भगवती दर्शन",
    when_en: "18m ago",
    when_hi: "18 मिनट पहले",
    stats: "❤️ 14.5K · 💬 890",
    post_url: "https://www.instagram.com/nitinnabinbjp/",
    sort_order: 1,
  },
  {
    id: "s-ig-1",
    platform: "ig",
    image_url: "https://i.ytimg.com/vi/xKYhZObZdNc/hq720.jpg",
    text_en: "Heartwarming glimpses from the Punjabi Gaurav Sammelan at Rudrapur, Uttarakhand with Hon'ble CM Pushkar Singh Dhami Ji. Sikh samaj's valor and devotion to Bharat inspire us endlessly! 🇮🇳✨",
    text_hi: "रुद्रपुर, उत्तराखंड में आयोजित 'पंजाबी गौरव सम्मेलन' की अविस्मरणीय झलकियाँ। मुख्यमंत्री श्री पुष्कर सिंह धामी जी के साथ सिख समाज के गौरव और देशभक्ति को नमन! 🇮🇳✨",
    label_en: "Rudrapur • Punjabi Sammelan",
    label_hi: "रुद्रपुर • पंजाबी सम्मेलन",
    when_en: "1 day ago",
    when_hi: "1 दिन पहले",
    stats: "❤️ 34.2K · 💬 1,420",
    post_url: "https://www.instagram.com/nitinnabinbjp/",
    sort_order: 2,
  },
  {
    id: "s-ig-2",
    platform: "ig",
    image_url: "https://i.ytimg.com/vi/PjeVmBTBQDs/hq720.jpg",
    text_en: "Inspiring interaction with energetic students and youth in Haldwani, Uttarakhand. Their innovative dreams and passion for nation-building are the true strength of Viksit Bharat! 🌟🚀",
    text_hi: "हल्द्वानी में युवा साथियों से प्रेरक संवाद! युवाओं का नवाचार, ऊर्जा और राष्ट्रसेवा का संकल्प ही विकसित भारत 2047 की सबसे बड़ी ताकत है! 🌟🚀",
    label_en: "Haldwani • Youth Conclave",
    label_hi: "हल्द्वानी • युवा संवाद",
    when_en: "2 days ago",
    when_hi: "2 दिन पहले",
    stats: "❤️ 29.8K · 💬 1,180",
    post_url: "https://www.instagram.com/nitinnabinbjp/",
    sort_order: 2,
  },
  {
    id: "s-ig-3",
    platform: "ig",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Nitin_Nabin%2C_National_President_of_Bharatiya_Janata_Party_meeting_with_the_President_of_India%2C_Droupadi_Murmu_at_Rashtrapati_Bhavan_%282025%29.jpg/1280px-Nitin_Nabin%2C_National_President_of_Bharatiya_Janata_Party_meeting_with_the_President_of_India%2C_Droupadi_Murmu_at_Rashtrapati_Bhavan_%282025%29.jpg",
    text_en: "Called on the Hon'ble President of India, Smt. Droupadi Murmu Ji at Rashtrapati Bhavan, New Delhi. A deeply humble and inspiring interaction on service to the nation. 🙏🇮🇳",
    text_hi: "राष्ट्रपति भवन में माननीय राष्ट्रपति श्रीमती द्रौपदी मुर्मू जी से शिष्टाचार भेंट। राष्ट्र निर्माण और जनसेवा के संकल्पों पर प्रेरक संवाद। 🙏🇮🇳",
    label_en: "Rashtrapati Bhavan",
    label_hi: "राष्ट्रपति भवन",
    when_en: "1 week ago",
    when_hi: "1 सप्ताह पहले",
    stats: "❤️ 48.6K · 💬 2,150",
    post_url: "https://www.instagram.com/nitinnabinbjp/",
    sort_order: 3,
  },
  {
    id: "s-ig-4",
    platform: "ig",
    image_url: "https://i.ytimg.com/vi/7K3V1o9SA1Y/hq720.jpg",
    text_en: "Honoring our brave ex-servicemen and veterans at Haldwani, Uttarakhand. Their courage and dedication will always lead our path. 🇮🇳❤️",
    text_hi: "हल्द्वानी में पूर्व सैनिक सम्मेलन: राष्ट्र सेवा में सर्वस्व समर्पित करने वाले वीर सैनिकों का सम्मान। उनका शौर्य सदैव हमारा पथ आलोकित करेगा। 🇮🇳❤️",
    label_en: "Ex-Servicemen • Haldwani",
    label_hi: "पूर्व सैनिक सम्मेलन • हल्द्वानी",
    when_en: "2 days ago",
    when_hi: "2 दिन पहले",
    stats: "❤️ 52.1K · 💬 2,640",
    post_url: "https://www.instagram.com/nitinnabinbjp/",
    sort_order: 4,
  },
  {
    id: "s-ig-5",
    platform: "ig",
    image_url: "https://i.ytimg.com/vi/bRmYiNLjikM/hq720.jpg",
    text_en: "Special address at the Central Party Headquarters in New Delhi announcing the nationwide Seva Sankalp Abhiyan! 🏛️✨",
    text_hi: "केंद्रीय पार्टी मुख्यालय, नई दिल्ली में सेवा संकल्प अभियान की औपचारिक घोषणा। 17 सितंबर से 17 अक्टूबर तक राष्ट्रव्यापी सेवा कार्य! 🏛️✨",
    label_en: "BJP Central HQ • New Delhi",
    label_hi: "भाजपा केंद्रीय मुख्यालय",
    when_en: "3 days ago",
    when_hi: "3 दिन पहले",
    stats: "❤️ 41.3K · 💬 1,870",
    post_url: "https://www.instagram.com/nitinnabinbjp/",
    sort_order: 5,
  },
  {
    id: "s-ig-6",
    platform: "ig",
    image_url: "https://i.ytimg.com/vi/BOx2eeNKgSA/hq720.jpg",
    text_en: "Behind the scenes: National interview discussing grassroots empowerment, youth leadership, and Viksit Bharat 2047. 📺🎙️",
    text_hi: "राष्ट्रीय साक्षात्कार के दौरान: जमीनी स्तर पर संगठन विस्तार, युवा नेतृत्व और विकसित भारत 2047 पर सार्थक परिचर्चा। 📺🎙️",
    label_en: "National Interview",
    label_hi: "राष्ट्रीय साक्षात्कार",
    when_en: "1 week ago",
    when_hi: "1 सप्ताह पहले",
    stats: "❤️ 27.5K · 💬 980",
    post_url: "https://www.instagram.com/nitinnabinbjp/",
    sort_order: 6,
  },
  {
    id: "s-ig-7",
    platform: "ig",
    image_url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Nitish_Kumar_inaugurating_JP_path_of_Ganga_Path.jpg/1280px-Nitish_Kumar_inaugurating_JP_path_of_Ganga_Path.jpg",
    text_en: "JP Ganga Path: Transforming infrastructure and urban mobility in Bihar! Dedicated to world-class connectivity and public welfare. 🛣️🌉",
    text_hi: "जेपी गंगा पथ: बिहार के बुनियादी ढाँचे और सुगम यातायात में ऐतिहासिक बदलाव! विश्वस्तरीय कनेक्टिविटी और जनहित को सतत समर्पित। 🛣️🌉",
    label_en: "JP Ganga Path • Patna",
    label_hi: "जेपी गंगा पथ • पटना",
    when_en: "1 month ago",
    when_hi: "1 माह पहले",
    stats: "❤️ 38.9K · 💬 1,540",
    post_url: "https://www.instagram.com/nitinnabinbjp/",
    sort_order: 7,
  },
  {
    id: "s-ig-8",
    platform: "ig",
    image_url: "https://i.ytimg.com/vi/5Mn1YXcmYAM/hq720_2.jpg",
    text_en: "Heartfelt interaction with students in Uttarakhand. Public trust is our greatest strength, and service to society is our highest duty. 🌸🙏",
    text_hi: "उत्तराखंड में विद्यार्थियों से आत्मीय संवाद। जनविश्वास ही हमारी शक्ति है और जनसेवा ही हमारा सर्वोच्च कर्तव्य। 🌸🙏",
    label_en: "Yuva Samvad • Uttarakhand",
    label_hi: "युवा संवाद • उत्तराखंड",
    when_en: "2 days ago",
    when_hi: "2 दिन पहले",
    stats: "❤️ 33.4K · 💬 1,290",
    post_url: "https://www.instagram.com/nitinnabinbjp/",
    sort_order: 8,
  },

  // YouTube Live Feed (https://www.youtube.com/@BJP4India)
  {
    id: "yt-XuX7UaTw5yw",
    platform: "yt",
    image_url: "https://i.ytimg.com/vi/XuX7UaTw5yw/hq720_2.jpg",
    text_en: "BJP President Nitin Nabin asks, 'Where was Rahul Gandhi during national crises?' | PM Modi | Press Briefing",
    text_hi: "भाजपा अध्यक्ष नितिन नवीन का तीखा सवाल: 'राष्ट्रीय संकटों के समय कहाँ थे राहुल गांधी?' | प्रेस वार्ता",
    label_en: "Nitin Nabin Address",
    label_hi: "नितिन नवीन संबोधन",
    when_en: "1 day ago",
    when_hi: "1 दिन पहले",
    stats: "15.7K views",
    post_url: "https://www.youtube.com/watch?v=XuX7UaTw5yw",
    sort_order: 1,
  },
  {
    id: "yt-jaN0ztkmvyg",
    platform: "yt",
    image_url: "https://i.ytimg.com/vi/jaN0ztkmvyg/hq720_2.jpg",
    text_en: "BJP President Nitin Nabin Slams Congress Leadership Over Full Rendition of National Song Vande Mataram",
    text_hi: "राष्ट्रीय गीत वंदे मातरम् के गायन पर भाजपा राष्ट्रीय अध्यक्ष नितिन नवीन का कांग्रेस पर कड़ा प्रहार",
    label_en: "Nitin Nabin Address",
    label_hi: "नितिन नवीन संबोधन",
    when_en: "1 day ago",
    when_hi: "1 दिन पहले",
    stats: "2.5K views",
    post_url: "https://www.youtube.com/watch?v=jaN0ztkmvyg",
    sort_order: 2,
  },
  {
    id: "yt-CDGW3yMfukk",
    platform: "yt",
    image_url: "https://i.ytimg.com/vi/CDGW3yMfukk/hq720_2.jpg",
    text_en: "BJP President Nitin Nabin launches sharp attack on opposition politics | Viksit Bharat & Public Service",
    text_hi: "विपक्षी राजनीति पर भाजपा राष्ट्रीय अध्यक्ष नितिन नवीन का तीखा हमला | विकसित भारत एवं जनसेवा",
    label_en: "Nitin Nabin Address",
    label_hi: "नितिन नवीन संबोधन",
    when_en: "1 day ago",
    when_hi: "1 दिन पहले",
    stats: "9.2K views",
    post_url: "https://www.youtube.com/watch?v=CDGW3yMfukk",
    sort_order: 3,
  },
  {
    id: "yt-oV3bzAR1OhI",
    platform: "yt",
    image_url: "https://i.ytimg.com/vi/oV3bzAR1OhI/hq720.jpg",
    text_en: "Full Press Conference: BJP National President Nitin Nabin addresses national media at Central Headquarters",
    text_hi: "पूरी प्रेस वार्ता: भाजपा केंद्रीय मुख्यालय में राष्ट्रीय मीडिया को संबोधित करते राष्ट्रीय अध्यक्ष नितिन नवीन",
    label_en: "National Press Conference",
    label_hi: "राष्ट्रीय प्रेस वार्ता",
    when_en: "16 hours ago",
    when_hi: "16 घंटे पहले",
    stats: "188K views",
    post_url: "https://www.youtube.com/watch?v=oV3bzAR1OhI",
    sort_order: 4,
  },
  {
    id: "yt-OPUmYG0RGsw",
    platform: "yt",
    image_url: "https://i.ytimg.com/vi/OPUmYG0RGsw/hq720_2.jpg",
    text_en: "'1984 massacre of our brothers was historic injustice, PM Modi gave real honor': Nitin Nabin",
    text_hi: "'1984 का नरसंहार ऐतिहासिक अन्याय था, पीएम मोदी ने सिख समाज को दिया सच्चा सम्मान': नितिन नवीन",
    label_en: "Nitin Nabin Address",
    label_hi: "नितिन नवीन संबोधन",
    when_en: "19 hours ago",
    when_hi: "19 घंटे पहले",
    stats: "2.6K views",
    post_url: "https://www.youtube.com/watch?v=OPUmYG0RGsw",
    sort_order: 5,
  },
  {
    id: "yt-VCRq9Eqlldo",
    platform: "yt",
    image_url: "https://i.ytimg.com/vi/VCRq9Eqlldo/hq720.jpg",
    text_en: "LIVE: BJP National President Nitin Nabin addresses Punjabi Gaurav Sammelan in Rudrapur, Uttarakhand",
    text_hi: "लाइव: रुद्रपुर, उत्तराखंड में 'पंजाबी गौरव सम्मेलन' को संबोधित करते भाजपा राष्ट्रीय अध्यक्ष नितिन नवीन",
    label_en: "Rudrapur Live Broadcast",
    label_hi: "रुद्रपुर लाइव प्रसारण",
    when_en: "19 hours ago",
    when_hi: "19 घंटे पहले",
    stats: "8.6K views",
    post_url: "https://www.youtube.com/watch?v=VCRq9Eqlldo",
    sort_order: 6,
  },
  {
    id: "yt-IZVtxEM8fPQ",
    platform: "yt",
    image_url: "https://i.ytimg.com/vi/IZVtxEM8fPQ/hqdefault.jpg",
    text_en: "Sikh Community के सम्मान से लेकर BRICS तक! श्री Nitin Nabin जी का राष्ट्रीय संबोधन | BJP",
    text_hi: "Sikh Community के सम्मान से लेकर BRICS तक! श्री Nitin Nabin जी का राष्ट्रीय संबोधन | BJP",
    label_en: "Nitin Nabin Address",
    label_hi: "नितिन नवीन संबोधन",
    when_en: "2 days ago",
    when_hi: "2 दिन पहले",
    stats: "48K views",
    post_url: "https://www.youtube.com/watch?v=IZVtxEM8fPQ",
    sort_order: 7,
  },
  {
    id: "yt-nWvpx_vDwOw",
    platform: "yt",
    image_url: "https://i.ytimg.com/vi/nWvpx_vDwOw/hqdefault.jpg",
    text_en: "1984 सिख नरसंहार: 3 दशक बाद न्याय की लड़ाई को PM Modi ने दी नई दिशा | श्री Nitin Nabin | BJP",
    text_hi: "1984 सिख नरसंहार: 3 दशक बाद न्याय की लड़ाई को PM Modi ने दी नई दिशा | श्री Nitin Nabin | BJP",
    label_en: "Nitin Nabin Address",
    label_hi: "नितिन नवीन संबोधन",
    when_en: "3 days ago",
    when_hi: "3 दिन पहले",
    stats: "35K views",
    post_url: "https://www.youtube.com/watch?v=nWvpx_vDwOw",
    sort_order: 8,
  },
];

